###

# curl -X POST http://localhost:5000/login
#  -H "Content-Type: application/json"
#  -d '{
#    "username": "testuser",
#    "password": "TestPass123"
#  }'
POST http://localhost:5000/login
Content-Type: application/json

{
  "username": "testuser",
  "password": "TestPass123"
}

###

