###

# curl -X POST http://localhost:5000/register
#  -H "Content-Type: application/json"
#  -d '{
#    "username": "testuser",
#    "password": "TestPass123",
#    "name": "Test User",
#    "phone": "1234567890"
#  }'
POST http://localhost:5000/register
Content-Type: application/json

{
  "username": "testuser",
  "password": "TestPass123",
  "name": "Test User",
  "phone": "1234567890"
}

###

