CREATE DATABASE KN CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;


USE KN;
CREATE TABLE users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(50) NOT NULL UNIQUE,
    password VARCHAR(50) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


CREATE TABLE user_info (
    user_id INT PRIMARY KEY,
    name VARCHAR(50),
    phone VARCHAR(20)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;